### ISSUE TITLE
labels with numbers

### ISSUE THREAD

**Issue by mml1** [huinni/colmar-academy#2]
Try to not use numbers in html labels. Instead, write out the number like` footer-note-two`. For some of these labels, like ` footer-note-two` you may want to consider using an id instead of a class.

https://github.com/huinni/colmar-academy/blob/master/index.html#L169
https://github.com/huinni/colmar-academy/blob/master/index.html#L248
https://github.com/huinni/colmar-academy/blob/master/index.html#L270
https://github.com/huinni/colmar-academy/blob/master/index.html#L16

**Comment by huinni** [comment]
good idea. got it.
