### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by mml1** [huinni/colmar-academy#4]
### Criteria 1: HTML Structure  
* _Score Level:_ 3
* _Comment(s):_ 
 Fantastic work with your HTML. Excellent job using comments and divs to separate content. There were a few items you can approve upon. Check out the other issues to know which HTML items to improve. 

### Criteria 2: Visual Layout for Both Desktop and Mobile Sizes
* _Score Level:_ 4
* _Comment(s):_ 
Brilliant mobile and desktop design. You met did well meeting the spec. 
 
### Criteria 3: Responsive Design (Media Queries, Responsive Units, etc.)
* _Score Level:_ 4
* _Comment(s):_ 
Your images and divs are responsive and look well when resizing the browser window.
 
### Criteria 4: Visual Design and Accessibility (Color Palette, Typography, Transitions, etc.)
* _Score Level:_ 3
* _Comment(s):_ 
Overall, your typography was good. However, your links need some consistency. 
 
### Overall Score: 14/16
Great work 👍 . I can see you understand responsive design and are able to implement it. In terms of future challenges, try playing with css animations and using git commits.

**Comment by huinni** [comment]
Thank you!
